### ISSUE TITLE
Run Time With Noise vs No Noise

### ISSUE THREAD

**Issue by Jammy2211** [jkeger/arctic#21]
The following script compares two datasets arctic clocking.

https://github.com/Jammy2211/autocti_workspace_test/blob/main/imaging_ci/profiling/arctic/noise.py

The datasets are identical, except one has Gaussian noise added to it whereas the other does not.

The clocking times for arctic for these two datasets are:

```
Clocking Time = 2.2919435501098633
Clocking Time No Noise = 7.8446900844573975
```

Experiments I did previously the latter time was going up to 12 seconds, albeit I cant reproduce this now. This likely depends on the exact nature of the image I simulate, but the general slow-down for noiseless data is likely a generic problem.

I'll send the files on teams as github wont let me.

**Comment by rjmassey** [comment]
Fixed by cleaning up the watermark levels every so often, accessed by the optional `[parallel/serial]_prune_n_electrons` and `[parallel/serial]_prune_frequency` arguments. Default values of these work reasonably well on noise-free Euclid charge injection line data, and don't make anything significantly slower on noisy (e.g. HST) science images.
